import { ART_ASSET_IDS, artAssetPath } from "./art-registry";

/**
 * Mythic art paths generated by `pnpm art:build` from repo-root `/assets`.
 * Keep TSX imports routed through this module instead of hardcoding `/art/...`.
 */

export type ArtSuit = "spades" | "hearts" | "clubs" | "diamonds";
export type ArtCardRank = "A" | "K" | "Q" | "J";
export type ArtNumberRank = "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10";
export type ArtPointRank = "5" | "10";

const CARD_RANK_NAMES = {
  A: "ace",
  K: "king",
  Q: "queen",
  J: "jack",
} as const satisfies Record<ArtCardRank, string>;

const UI = {
  attackBadge: artAssetPath(ART_ASSET_IDS.gameplayUi("attack-badge")),
  defendBadge: artAssetPath(ART_ASSET_IDS.gameplayUi("defend-badge")),
  trumpDeclaration: artAssetPath(ART_ASSET_IDS.gameplayUi("trump-declaration")),
  buriedCards: artAssetPath(ART_ASSET_IDS.gameplayUi("buried-cards")),
  cardDeck: artAssetPath(ART_ASSET_IDS.gameplayUi("card-deck")),
  attackersBanner: artAssetPath(ART_ASSET_IDS.gameplayUi("attackers-banner")),
  defendersBanner: artAssetPath(ART_ASSET_IDS.gameplayUi("defenders-banner")),
  levelUpScore: artAssetPath(ART_ASSET_IDS.gameplayUi("level-up-score")),
  wordmark: artAssetPath(ART_ASSET_IDS.wordmark),
  trumpBurst: artAssetPath(ART_ASSET_IDS.trumpBurst),
  panelFrame: artAssetPath(ART_ASSET_IDS.panelFrame),
  nameplate: artAssetPath(ART_ASSET_IDS.playerNameplate),
  tableRing: artAssetPath(ART_ASSET_IDS.tableRing),
} as const;

const SPLASH = {
  victory: artAssetPath(ART_ASSET_IDS.splashVictory),
  defeat: artAssetPath(ART_ASSET_IDS.splashDefeat),
} as const;

const HOME = {
  heroLandscape: artAssetPath(ART_ASSET_IDS.heroLandscape),
  heroPortrait: artAssetPath(ART_ASSET_IDS.heroPortrait),
} as const;

const CARD = {
  premiumBack: artAssetPath(ART_ASSET_IDS.cardBack),
  parchmentSurface: artAssetPath(ART_ASSET_IDS.cardSurface),
  heartsFrame: artAssetPath(ART_ASSET_IDS.houseCardFrame("hearts")),
  spadesFrame: artAssetPath(ART_ASSET_IDS.houseCardFrame("spades")),
  diamondsFrame: artAssetPath(ART_ASSET_IDS.houseCardFrame("diamonds")),
  clubsFrame: artAssetPath(ART_ASSET_IDS.houseCardFrame("clubs")),
} as const;

const AVATARS = {
  hadesKingYan: artAssetPath(ART_ASSET_IDS.portrait("hades-king-yan")),
  persephonePlumBlossom: artAssetPath(
    ART_ASSET_IDS.portrait("persephone-plum-blossom"),
  ),
  poseidonDragonKing: artAssetPath(ART_ASSET_IDS.portrait("poseidon-dragon-king")),
  athenaGrandStrategist: artAssetPath(
    ART_ASSET_IDS.portrait("athena-grand-strategist"),
  ),
  thorThunderBrawler: artAssetPath(ART_ASSET_IDS.portrait("thor-thunder-brawler")),
  freyjaValkyrieQueen: artAssetPath(ART_ASSET_IDS.portrait("freyja-valkyrie-queen")),
  anubisJackalJudge: artAssetPath(ART_ASSET_IDS.portrait("anubis-jackal-judge")),
  changeMoonHuntress: artAssetPath(ART_ASSET_IDS.portrait("change-moon-huntress")),
} as const;

export function art2x(path: string): string {
  return path.replace(/(\.[^.]+)$/, "@2x$1");
}

export function artCardFace(suit: ArtSuit, rank: ArtCardRank): string {
  return artAssetPath(ART_ASSET_IDS.legacyCardFace(suit, CARD_RANK_NAMES[rank]));
}

export function artCardFace2x(suit: ArtSuit, rank: ArtCardRank): string {
  return art2x(artCardFace(suit, rank));
}

export function artJokerFace(size: "big" | "small"): string {
  return artAssetPath(ART_ASSET_IDS.legacyJoker(size));
}

export function artCardSurface(): string {
  return artAssetPath(ART_ASSET_IDS.cardSurface);
}

export function artHouseFrame(suit: ArtSuit): string {
  return artAssetPath(ART_ASSET_IDS.houseCardFrame(suit));
}

export function artTreasureIllustration(suit: ArtSuit, rank: ArtPointRank): string {
  return artAssetPath(
    ART_ASSET_IDS.treasureIllustration(suit, rank === "5" ? "five" : "ten"),
  );
}

export function artNumberRank(rank: ArtNumberRank, red: boolean): string {
  return artAssetPath(ART_ASSET_IDS.rankIndex(red ? "red" : "black", rank));
}

export function artSuitIcon(suit: ArtSuit): string {
  return artAssetPath(ART_ASSET_IDS.suitIndex(suit));
}

export const ART = {
  ui: UI,
  card: CARD,
  home: HOME,
  splash: SPLASH,
  avatars: AVATARS,
} as const;
