/**
 * Mythic art paths generated by `pnpm art:build` from repo-root `/assets`.
 * Keep TSX imports routed through this module instead of hardcoding `/art/...`.
 */

export type ArtSuit = "spades" | "hearts" | "clubs" | "diamonds";
export type ArtCardRank = "A" | "K" | "Q" | "J";

const CARD_RANK_NAMES = {
  A: "ace",
  K: "king",
  Q: "queen",
  J: "jack",
} as const satisfies Record<ArtCardRank, string>;

const UI = {
  attackBadge: "/art/ui/attack-badge.webp",
  defendBadge: "/art/ui/defend-badge.webp",
  trumpDeclaration: "/art/ui/trump-declaration.webp",
  buriedCards: "/art/ui/buried-cards.webp",
  cardDeck: "/art/ui/card-deck.webp",
  pointsGlow: "/art/ui/points-glow.webp",
  attackersBanner: "/art/ui/attackers-banner.webp",
  defendersBanner: "/art/ui/defenders-banner.webp",
  levelUpScore: "/art/ui/level-up-score.webp",
} as const;

const SPLASH = {
  victory: "/art/splash/victory.webp",
  defeat: "/art/splash/defeat.webp",
} as const;

const AVATARS = {
  hadesKingYan: "/art/avatars/hades-king-yan.webp",
} as const;

export function art2x(path: string): string {
  return path.replace(/(\.[^.]+)$/, "@2x$1");
}

export function artCardFace(suit: ArtSuit, rank: ArtCardRank): string {
  return `/art/cards/${suit}-${CARD_RANK_NAMES[rank]}.webp`;
}

export function artCardFace2x(suit: ArtSuit, rank: ArtCardRank): string {
  return art2x(artCardFace(suit, rank));
}

export const ART = {
  ui: UI,
  splash: SPLASH,
  avatars: AVATARS,
} as const;
