/**
 * Mythic art paths generated by `pnpm art:build` from repo-root `/assets`.
 * Keep TSX imports routed through this module instead of hardcoding `/art/...`.
 */

export type ArtSuit = "spades" | "hearts" | "clubs" | "diamonds";
export type ArtCardRank = "A" | "K" | "Q" | "J";

const CARD_RANK_NAMES = {
  A: "ace",
  K: "king",
  Q: "queen",
  J: "jack",
} as const satisfies Record<ArtCardRank, string>;

const UI = {
  attackBadge: "/art/ui/attack-badge.webp",
  defendBadge: "/art/ui/defend-badge.webp",
  trumpDeclaration: "/art/ui/trump-declaration.webp",
  buriedCards: "/art/ui/buried-cards.webp",
  cardDeck: "/art/ui/card-deck.webp",
  pointsGlow: "/art/ui/points-glow.webp",
  attackersBanner: "/art/ui/attackers-banner.webp",
  defendersBanner: "/art/ui/defenders-banner.webp",
  levelUpScore: "/art/ui/level-up-score.webp",
  wordmark: "/art/ui/sheng-ji-wordmark.webp",
  trumpFrame: "/art/ui/trump-frame.webp",
  trumpFrameCompact: "/art/ui/trump-frame-compact.webp",
  trumpSeal: "/art/ui/trump-seal.webp",
  trumpBurst: "/art/ui/trump-burst.webp",
  panelFrame: "/art/ui/panel-frame.webp",
  nameplate: "/art/ui/nameplate.webp",
  tableRing: "/art/ui/table-ring.webp",
  pointGlowFive: "/art/ui/point-glow-five.webp",
  pointGlowTen: "/art/ui/point-glow-ten.webp",
  pointGlowKing: "/art/ui/point-glow-king.webp",
} as const;

const SPLASH = {
  victory: "/art/splash/victory.webp",
  defeat: "/art/splash/defeat.webp",
} as const;

const HOME = {
  heroLandscape: "/art/home/hero-landscape.webp",
  heroPortrait: "/art/home/hero-portrait.webp",
} as const;

const CARD = {
  premiumBack: "/art/cards/card-back.webp",
  heartsNumberBlank: "/art/cards/hearts-number-blank.webp",
  spadesNumberBlank: "/art/cards/spades-number-blank.webp",
  diamondsNumberBlank: "/art/cards/diamonds-number-blank.webp",
  clubsNumberBlank: "/art/cards/clubs-number-blank.webp",
  heartsPip: "/art/cards/hearts-pip.webp",
  spadesPip: "/art/cards/spades-pip.webp",
  diamondsPip: "/art/cards/diamonds-pip.webp",
  clubsPip: "/art/cards/clubs-pip.webp",
} as const;

const AVATARS = {
  hadesKingYan: "/art/avatars/hades-king-yan.webp",
  persephonePlumBlossom: "/art/avatars/persephone-plum-blossom.webp",
  poseidonDragonKing: "/art/avatars/poseidon-dragon-king.webp",
  athenaGrandStrategist: "/art/avatars/athena-grand-strategist.webp",
} as const;

export function art2x(path: string): string {
  return path.replace(/(\.[^.]+)$/, "@2x$1");
}

export function artCardFace(suit: ArtSuit, rank: ArtCardRank): string {
  return `/art/cards/${suit}-${CARD_RANK_NAMES[rank]}.webp`;
}

export function artCardFace2x(suit: ArtSuit, rank: ArtCardRank): string {
  return art2x(artCardFace(suit, rank));
}

export const ART = {
  ui: UI,
  card: CARD,
  home: HOME,
  splash: SPLASH,
  avatars: AVATARS,
} as const;
