import type { BotConfig, BotDifficulty } from "./types.js";

export const BOT_CONFIGS = {
  beginner: {
    difficulty: "beginner",
    temperature: 1.6,
    blunderRate: 0.15,
    candidateLimit: 3,
    cardCounting: false,
    voidInference: false,
    teamCoordination: "none",
    pointManagement: false,
    trumpConservation: false,
    throws: "never",
    endgameAwareness: false,
    bidAggression: 0.6,
    bidTiming: 0,
    counterBid: "never",
    buryQuality: "basic",
  },
  intermediate: {
    difficulty: "intermediate",
    temperature: 0.9,
    blunderRate: 0.06,
    cardCounting: false,
    voidInference: false,
    teamCoordination: "winner",
    pointManagement: true,
    trumpConservation: true,
    throws: "never",
    endgameAwareness: false,
    bidAggression: 0.433,
    bidTiming: 0.35,
    counterBid: "pair-only",
    buryQuality: "points",
  },
  advanced: {
    difficulty: "advanced",
    temperature: 0.45,
    blunderRate: 0.015,
    cardCounting: true,
    voidInference: true,
    teamCoordination: "full",
    pointManagement: true,
    trumpConservation: true,
    throws: "safe-limited",
    endgameAwareness: true,
    bidAggression: 0.367,
    bidTiming: 0.5,
    counterBid: "strong",
    buryQuality: "voids",
  },
  expert: {
    difficulty: "expert",
    temperature: 0.12,
    blunderRate: 0,
    cardCounting: true,
    voidInference: true,
    teamCoordination: "full",
    pointManagement: true,
    trumpConservation: true,
    throws: "safe",
    endgameAwareness: true,
    bidAggression: 0.3,
    bidTiming: 0.62,
    counterBid: "full",
    buryQuality: "endgame",
  },
} as const satisfies Record<BotDifficulty, BotConfig>;

export function botConfigForDifficulty(difficulty: BotDifficulty): BotConfig {
  return BOT_CONFIGS[difficulty];
}
